name: tf-deploy

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  tf-deploy:
    uses: ./.github/workflows/.tf-deploy.yml
    with:
      environment: snowflake-preview
      account_id: "ukmixxl-yb13574"
    secrets: inherit
    concurrency:
      group: ${{ github.workflow }}-ci-run
      cancel-in-progress: false
