name: terraform

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  terraform:
    uses: ./.github/workflows/.terraform.yml
    with:
      account_id: "ukmixxl-yb13574"
    secrets: inherit
